/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-02-07 11:11:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WebContent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import logic.controllers.ViewShopController;
import logic.entities.Shop;

public final class viewShops_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	ArrayList<Shop> shops;
	int i=0;
	
	public void nextShop()
	{
		shops = ViewShopController.getInstance().getList();
		if(shops==null)
		{
			//out.println("There is no dhop in our Data Base");
		}
		else
		{
			if(i>=shops.size())
			{
				i=0;
			}
			if(i<0)
			{
				i=shops.size()-1;
			}
			this.setLabels();
		}
		i++;
	}
	
	public void previousShop()
	{
		shops = ViewShopController.getInstance().getList();
		if(shops==null)
		{
			

		}
		else
		{
			if(i>=shops.size())
			{
				i=shops.size()-2;
			}
			if(i<0)
			{
				i=shops.size()-1;
			}
			this.setLabels();
		}
		i--;
	}
	
	public void setLabels()
	{
		SimpleDateFormat sdf; 
		
		//application.setAttribute("name",shops.get(i).getNome());
		//request.setAttribute("address",shops.get(i).getIndirizzo());
		//request.setAttribute("area",shops.get(i).getZona());
		//request.setAttribute("municipality",shops.get(i).getComune());
		//request.setAttribute("username",shops.get(i).getUsername());
		//String date = new SimpleDateFormat("dd-MM-yyyy").format(shops.get(i).getData());
		//request.setAttribute("data",date);
		//request.setAttribute("descrizione",shops.get(i).getDescrizione());
	}
	
	

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("logic.controllers.ViewShopController");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("logic.entities.Shop");
    _jspx_imports_classes.add("java.time.ZoneId");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n    \n\n\n\n\n<!DOCTYPE html>\n<html lang=\"it\">\n<head>\n<meta charset=\"ISO-8859-1\">\n<title>View Shops</title>\n</head>\n<body>\n");
      out.write("\n\t\t\t<p>There is no shop in our database</p>\n\t\t\t");
      out.write("\n\t<div>\n\t\t<h1 id = \"title\" >SkateSpot</h1>\n\t\t<a href=\"index.jsp\">\n\t\t\t<img src=\"images/home_icon.png\" alt=\"BACK\"/>\n\t\t</a>\n\t</div>\n\t\n\t<div>\n\t\t<h1>Shop details</h1> <br><br>\n\t\t<label>Shop name : </label>\n\t\t<label for=\"name\" id=\"name\"> Name </label> <br><br>\n\t\t<label>Address : </label>\n\t\t<label for=\"address\" id=\"address\"> Address </label> <br><br>\n\t\t<label>Area : </label>\n\t\t<label for=\"area\" id=\"area\"> Area </label> <br><br>\n\t\t<label>Municipality : </label>\n\t\t<label for=\"municipality\" id=\"municipality\"> Municipality </label> <br><br>\n\t\t<label>Description : </label>\n\t\t<label for=\"description\" id=\"description\"> Description </label> <br><br>\n\t\t<label> Added by :</label>\n\t\t<label for=\"owner\" id=\"owner\"> Owner </label><br><br>\n\t\t<label> On :</label>\n\t\t<label for=\"date\" id=\"date\"> Date </label><br><br><br>\n\t\t<input type=\"submit\" value=\"PREVIOUS\" onClick=\"previousShop()\"/>\n\t\t<input type=\"submit\" value=\"NEXT\" onClick=\"nextShop()\"/>\n\t\t\n\t</div>\n\t\n</body>\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
